name: stubb
title: "Stubb"
summary: "A Docker utility by CircleCI."
description: |
  Stubb is a Docker utility that allows you to display information on Docker images, tags, and layers as well as Docker Hub metrics.
license: MIT
base: core18
grade: stable
confinement: strict
adopt-info: stubb
icon: "img/circleci-logo.svg"

parts:
  stubb:
    plugin: dump
    source: .
    override-build: |
      snapcraftctl build

      cp src/dist/stubb_linux_amd64/stubb $SNAPCRAFT_PART_INSTALL

      chmod +x $SNAPCRAFT_PART_INSTALL/stubb

      snapcraftctl set-version $(cat VERSION)

apps:
  stubb:
    command: stubb
    plugs:
      - home
      - network
